---
language: go

go:
  - "1.12.x"

env:
  global:
    - GO111MODULE=on

script:
  - env GO111MODULE=on go test -v ./...

after_script:
  - curl -d "repo=github.com/zpxio/heromanager" https://goreportcard.com/checks
